[package]
name = "reader"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Markdown to HTML converter"
repository.workspace = true
license-file.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
utils.workspace = true
