[package]
name = "parser"
version = "0.1.0"
authors = ["robertpakalns"]
edition = "2024"
description = "HTML to Markdown parser, designed for working with letonika.lv resources"
repository = "https://github.com/robertpakalns/letonikabc"
license-file = "../../LICENSE"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
