on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - run: rustup target add wasm32-unknown-unknown

      # Install Binaryen
      - run: |
          v=125
          wget https://github.com/WebAssembly/binaryen/releases/download/version_${v}/binaryen-version_${v}-x86_64-linux.tar.gz
          tar -xzf binaryen-version_${v}-x86_64-linux.tar.gz
          echo "$PWD/binaryen-version_${v}/bin" >> $GITHUB_PATH

      # Install wasm-bindgen CLI
      - run: |
          v=0.2.106
          wget https://github.com/wasm-bindgen/wasm-bindgen/releases/download/${v}/wasm-bindgen-${v}-x86_64-unknown-linux-musl.tar.gz
          tar -xzf wasm-bindgen-${v}-x86_64-unknown-linux-musl.tar.gz
          echo "$PWD/wasm-bindgen-${v}-x86_64-unknown-linux-musl" >> $GITHUB_PATH

      - run: bun install
      - run: bun run build

      - run: touch dist/.nojekyll

      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
